-- Student Interest Matcher schema (users, interests, user_interests)

-- 1) Users table
create table if not exists users (
  id bigint generated by default as identity primary key,
  name text,
  class text,
  rollno text,
  email text,
  phone text,
  whatsapp text,
  instagram text,
  password text,
  created_at timestamp with time zone default now()
);

-- migration-safe adjustments for existing installations
alter table users add column if not exists name text;
alter table users add column if not exists class text;
alter table users add column if not exists rollno text;
alter table users add column if not exists email text;
alter table users add column if not exists phone text;
alter table users add column if not exists whatsapp text;
alter table users add column if not exists instagram text;
alter table users add column if not exists password text;
alter table users add column if not exists created_at timestamp with time zone default now();

alter table users drop column if exists auth_user_id;
alter table users drop constraint if exists users_email_kitsw_check;

create unique index if not exists users_email_unique_idx on users(email);

-- 2) Interests table
create table if not exists interests (
  id bigint generated by default as identity primary key,
  name text not null unique
);

-- 3) Many-to-many bridge table
create table if not exists user_interests (
  user_id bigint not null references users(id) on delete cascade,
  interest_id bigint not null references interests(id) on delete cascade,
  primary key (user_id, interest_id)
);

-- Helpful indexes for matching queries
create index if not exists idx_user_interests_user_id on user_interests(user_id);
create index if not exists idx_user_interests_interest_id on user_interests(interest_id);

-- Query A: get one user's interests
-- select i.id, i.name
-- from user_interests ui
-- join interests i on i.id = ui.interest_id
-- where ui.user_id = :target_user_id
-- order by i.name;

-- Query B: match users by common interests count (excluding current user)
-- select
--   u.id,
--   u.name,
--   u.class,
--   u.rollno,
--   u.email,
--   u.phone,
--   u.whatsapp,
--   u.instagram,
--   count(*) as common_interest_count
-- from user_interests my_ui
-- join user_interests other_ui on other_ui.interest_id = my_ui.interest_id
-- join users u on u.id = other_ui.user_id
-- where my_ui.user_id = :target_user_id
--   and other_ui.user_id <> :target_user_id
-- group by u.id, u.name, u.class, u.rollno, u.email, u.phone, u.whatsapp, u.instagram
-- order by common_interest_count desc, u.name asc;

-- RPC: directly callable via supabase.rpc('get_student_matches', { target_user_id: 1 })
create or replace function get_student_matches(target_user_id bigint)
returns table (
  id bigint,
  name text,
  class text,
  rollno text,
  email text,
  phone text,
  whatsapp text,
  instagram text,
  common_interest_count bigint
)
language sql
stable
as $$
  select
    u.id,
    u.name,
    u.class,
    u.rollno,
    u.email,
    u.phone,
    u.whatsapp,
    u.instagram,
    count(*) as common_interest_count
  from user_interests my_ui
  join user_interests other_ui on other_ui.interest_id = my_ui.interest_id
  join users u on u.id = other_ui.user_id
  where my_ui.user_id = target_user_id
    and other_ui.user_id <> target_user_id
  group by u.id, u.name, u.class, u.rollno, u.email, u.phone, u.whatsapp, u.instagram
  order by common_interest_count desc, u.name asc;
$$;

-- RPC: fetch interests for one user via supabase.rpc('get_user_interests', { target_user_id: 1 })
create or replace function get_user_interests(target_user_id bigint)
returns table (
  id bigint,
  name text
)
language sql
stable
as $$
  select i.id, i.name
  from user_interests ui
  join interests i on i.id = ui.interest_id
  where ui.user_id = target_user_id
  order by i.name;
$$;
